# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest
  
variables:
  uiSource: 'src'
  uiBuild: '$(uiSource)/build'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- bash: echo $(Build.SourcesDirectory)
- bash: echo $(Build.BuildId)
- bash: echo $(Build.BuildNumber)
- bash: echo $(System.DefaultWorkingDirectory)
- bash: echo $(Build.ArtifactStagingDirectory)

- script: |
    pushd $(uiSource)
    npm install
    npm run build
    popd 
  displayName: 'npm install and build'
- bash: echo $(Build.ArtifactStagingDirectory)
- bash: ls -R $(Build.ArtifactStagingDirectory)
- bash: ls -R $(System.DefaultWorkingDirectory)
- bash: ls -R $(uiBuild)
- bash: ls -R $(uiSource)
# - task: ArchiveFiles@2
#   inputs:
#     rootFolderOrFile: '$(uiBuild)'
#     includeRootFolder: false
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
#     replaceExistingArchive: true
# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'

